spring:
  datasource:
    password: ${DB_PASSWORD:user_service_dev_pw}

  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.flywaydb: INFO

integration:
  merchant-service:
    enabled: ${MERCHANT_SYNC_ENABLED:false}
